db:
    image: postgres
    ports:
        - "5432"

web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - .:/petmarket
    ports:
        - "3000:3000"
    links:
        - db
