# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f854dbbf8f911e2dcd2f8feb0fe61239560ce4177c3820dad2f9f73e279fa177498967380eb1e8bf9bfb8350182ea534dfc5a5fab101262f54fe8d5668b262d

test:
  secret_key_base: b52166cc817e7f99013bc055cf529014870650879e43b9ac8c05032deae8da514758f96d134b5a75e07afee88d66a92f621f832bd71d0c21924211e25f940c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
